DROP TABLE IF EXISTS FILMAGENDA;
CREATE TABLE FILMAGENDA(ID BIGINT AUTO_INCREMENT, TITEL VARCHAR(255), DATUM DATE);
INSERT INTO FILMAGENDA (TITEL, DATUM) VALUES('The Legend of Tarzan (2016)', '2016-01-25');
INSERT INTO FILMAGENDA (TITEL, DATUM) VALUES('Tarzan (1999)', '2016-02-01');
SELECT * FROM FILMAGENDA ORDER BY ID;
